lst=['Apple','Guava','Mango','Banana','Kiwi']
print("lingth of list:", len(lst))
print("first element:",lst[0])
print("Last element:",lst[-1])
lst.append('Papaya')
print("updated list:",lst)
lst.remove('Guava')
print("updated list:",lst)
lst.sort()
print("Sorted list:",lst)
lst.pop(1)
print("updated list:",lst)
lst.reverse()
print("Reversed list:",lst)
print("multiplicationon list:",lst*2)
lst=lst[:4]
print("Sliced list:",lst)
lst.clear()
print("updated list:",lst)