file = open('C:\\Users\\rajav\\Downloads\\Codingal.txt','r')
print(file.read())
file.close()
file = open('C:\\Users\\rajav\\Downloads\\Codingal.txt','r')
print(file.read(8))
file.close()
file = open('C:\\Users\\rajav\\Downloads\\Codingal.txt','a')
file.write("hi! I am rakshitha and I am 13 yr old.")
file.close()